# A workflow to run Bazel builds and tests.

name: precommit

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'gamma'
      - 'macos'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install infrastructure
        run: |
          #curl -fsSL https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          #sudo apt-get install software-properties-common
          #sudo apt-add-repository 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
          #sudo apt-get update
          sudo apt-get install libffi-dev gettext freeglut3-dev libsdl2-dev zip libosmesa6-dev python-dev python-numpy python-pil python3-dev python3-numpy python3-pil
      - name: build
        run: |
          bazel --bazelrc=.precommit.bazelrc build --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //...
      - name: run-tests
        timeout-minutes: 45
        run: |
          bazel --bazelrc=.precommit.bazelrc test  --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //python/tests:all |& tee onerun.log
          #bazel --bazelrc=.precommit.bazelrc test  --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //... |& tee onerun.log
          grep onerun.log -e '^\s*/home.*python_module_test.*test\.log' | xargs echo "Log files: "
          echo -e "Printing:\n****"
          grep onerun.log -e '^\s*/home.*python_module_test.*test\.log' | xargs cat
          echo -e "\n****\nPrinting done."
      - name: run-agent
        run: |
          bazel --bazelrc=.precommit.bazelrc run   --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare --define headless=osmesa //:python_random_agent
